package ServerObjectInterfacezApp;


/**
* ServerObjectInterfacezApp/ServerObjectInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/ServerObjectInterface.idl
* Wednesday, 23 February, 2022 2:13:40 PM EST
*/

public interface ServerObjectInterface extends ServerObjectInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerObjectInterface
