package ServerObjectInterfacezApp;


/**
* ServerObjectInterfacezApp/ServerObjectInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/ServerObjectInterface.idl
* Wednesday, 23 February, 2022 2:13:40 PM EST
*/

public abstract class ServerObjectInterfacePOA extends org.omg.PortableServer.Servant
 implements ServerObjectInterfacezApp.ServerObjectInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addAppointment", new java.lang.Integer (0));
    _methods.put ("removeAppointment", new java.lang.Integer (1));
    _methods.put ("listAppointmentAvailability", new java.lang.Integer (2));
    _methods.put ("bookAppointment", new java.lang.Integer (3));
    _methods.put ("getAppointmentSchedule", new java.lang.Integer (4));
    _methods.put ("cancelAppointment", new java.lang.Integer (5));
    _methods.put ("swapAppointment", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServerObjectInterfacezApp/ServerObjectInterface/addAppointment
       {
         String adminId = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         int capacity = in.read_long ();
         boolean $result = false;
         $result = this.addAppointment (adminId, appointmentID, appointmentType, capacity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ServerObjectInterfacezApp/ServerObjectInterface/removeAppointment
       {
         String adminId = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         int capacity = in.read_long ();
         boolean $result = false;
         $result = this.removeAppointment (adminId, appointmentID, appointmentType, capacity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ServerObjectInterfacezApp/ServerObjectInterface/listAppointmentAvailability
       {
         String adminId = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.listAppointmentAvailability (adminId, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ServerObjectInterfacezApp/ServerObjectInterface/bookAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         boolean $result = false;
         $result = this.bookAppointment (patientID, appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // ServerObjectInterfacezApp/ServerObjectInterface/getAppointmentSchedule
       {
         String patientID = in.read_string ();
         String $result = null;
         $result = this.getAppointmentSchedule (patientID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ServerObjectInterfacezApp/ServerObjectInterface/cancelAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         boolean $result = false;
         $result = this.cancelAppointment (patientID, appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // ServerObjectInterfacezApp/ServerObjectInterface/swapAppointment
       {
         String patientID = in.read_string ();
         String oldAppointmentID = in.read_string ();
         String oldAppointmentType = in.read_string ();
         String newAppointmentID = in.read_string ();
         String newAppointmentType = in.read_string ();
         boolean $result = false;
         $result = this.swapAppointment (patientID, oldAppointmentID, oldAppointmentType, newAppointmentID, newAppointmentType);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // ServerObjectInterfacezApp/ServerObjectInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerObjectInterfacezApp/ServerObjectInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerObjectInterface _this() 
  {
    return ServerObjectInterfaceHelper.narrow(
    super._this_object());
  }

  public ServerObjectInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ServerObjectInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ServerObjectInterfacePOA
