package ServerObjectInterfacezApp;


/**
* ServerObjectInterfacezApp/ServerObjectInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/ServerObjectInterface.idl
* Wednesday, 23 February, 2022 2:13:40 PM EST
*/

abstract public class ServerObjectInterfaceHelper
{
  private static String  _id = "IDL:ServerObjectInterfacezApp/ServerObjectInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, ServerObjectInterfacezApp.ServerObjectInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServerObjectInterfacezApp.ServerObjectInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServerObjectInterfacezApp.ServerObjectInterfaceHelper.id (), "ServerObjectInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServerObjectInterfacezApp.ServerObjectInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerObjectInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServerObjectInterfacezApp.ServerObjectInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServerObjectInterfacezApp.ServerObjectInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerObjectInterfacezApp.ServerObjectInterface)
      return (ServerObjectInterfacezApp.ServerObjectInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerObjectInterfacezApp._ServerObjectInterfaceStub stub = new ServerObjectInterfacezApp._ServerObjectInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServerObjectInterfacezApp.ServerObjectInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerObjectInterfacezApp.ServerObjectInterface)
      return (ServerObjectInterfacezApp.ServerObjectInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerObjectInterfacezApp._ServerObjectInterfaceStub stub = new ServerObjectInterfacezApp._ServerObjectInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
