package ServerObjectInterfacezApp;


/**
* ServerObjectInterfacezApp/ServerObjectInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/ServerObjectInterface.idl
* Wednesday, 23 February, 2022 2:13:40 PM EST
*/

public interface ServerObjectInterfaceOperations 
{
  boolean addAppointment (String adminId, String appointmentID, String appointmentType, int capacity);
  boolean removeAppointment (String adminId, String appointmentID, String appointmentType, int capacity);
  String listAppointmentAvailability (String adminId, String appointmentType);
  boolean bookAppointment (String patientID, String appointmentID, String appointmentType);
  String getAppointmentSchedule (String patientID);
  boolean cancelAppointment (String patientID, String appointmentID, String appointmentType);
  boolean swapAppointment (String patientID, String oldAppointmentID, String oldAppointmentType, String newAppointmentID, String newAppointmentType);
  void shutdown ();
} // interface ServerObjectInterfaceOperations
