
package interfaceimplimentation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Sherbrooke_ClassService", targetNamespace = "http://InterfaceImplimentation/", wsdlLocation = "file:/D:/Eclips_2o2o_6/A3/src/she.wsdl")
public class SherbrookeClassService
    extends Service
{

    private final static URL SHERBROOKECLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHERBROOKECLASSSERVICE_EXCEPTION;
    private final static QName SHERBROOKECLASSSERVICE_QNAME = new QName("http://InterfaceImplimentation/", "Sherbrooke_ClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Eclips_2o2o_6/A3/src/she.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHERBROOKECLASSSERVICE_WSDL_LOCATION = url;
        SHERBROOKECLASSSERVICE_EXCEPTION = e;
    }

    public SherbrookeClassService() {
        super(__getWsdlLocation(), SHERBROOKECLASSSERVICE_QNAME);
    }

    public SherbrookeClassService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHERBROOKECLASSSERVICE_QNAME, features);
    }

    public SherbrookeClassService(URL wsdlLocation) {
        super(wsdlLocation, SHERBROOKECLASSSERVICE_QNAME);
    }

    public SherbrookeClassService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHERBROOKECLASSSERVICE_QNAME, features);
    }

    public SherbrookeClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SherbrookeClassService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "Sherbrooke_ClassPort")
    public WebInterface getSherbrookeClassPort() {
        return super.getPort(new QName("http://InterfaceImplimentation/", "Sherbrooke_ClassPort"), WebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "Sherbrooke_ClassPort")
    public WebInterface getSherbrookeClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://InterfaceImplimentation/", "Sherbrooke_ClassPort"), WebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHERBROOKECLASSSERVICE_EXCEPTION!= null) {
            throw SHERBROOKECLASSSERVICE_EXCEPTION;
        }
        return SHERBROOKECLASSSERVICE_WSDL_LOCATION;
    }

}
